# calculating return values and periods using climextremes

In [1]:
import requests 
import numpy as np
import pandas as pd
import xarray as xr
from datetime import datetime

import climextremes as climext

import matplotlib.pyplot as plt
%matplotlib inline

## extracting time series from netcdf file

In [2]:
ds = xr.open_dataset("./data/pr_Amon_NorESM1-M_historical_r1i1p1_185001-200512.nc")
ds

<xarray.Dataset>
Dimensions:    (time: 1872, bnds: 2, lat: 96, lon: 144)
Coordinates:
  * time       (time) object 1850-01-16 12:00:00 ... 2005-12-16 12:00:00
  * lat        (lat) float64 -90.0 -88.11 -86.21 -84.32 ... 86.21 88.11 90.0
  * lon        (lon) float64 0.0 2.5 5.0 7.5 10.0 ... 350.0 352.5 355.0 357.5
Dimensions without coordinates: bnds
Data variables:
    time_bnds  (time, bnds) object ...
    lat_bnds   (lat, bnds) float64 ...
    lon_bnds   (lon, bnds) float64 ...
    pr         (time, lat, lon) float32 ...
Attributes: (12/26)
    institution:            Norwegian Climate Centre
    institute_id:           NCC
    experiment_id:          historical
    source:                 NorESM1-M 2011  atmosphere: CAM-Oslo (CAM4-Oslo-n...
    model_id:               NorESM1-M
    forcing:                GHG, SA, Oz, Sl, Vl, BC, OC
    ...                     ...
    table_id:               Table Amon (27 April 2011) a5a1c518f52ae340313ba0...
    title:                  NorESM1-M model output prepared for CMIP5 historical
    parent_experiment:      pre-industrial control
    modeling_realm:         atmos
    realization:            1
    cmor_version:           2.6.0

In [3]:
# converting precipitation to m/day units

ds["pr"].data = ds["pr"].data * 86400
ds["pr"].attrs["units"] = 'mm/day' 

In [4]:
# getting dataset specifically for defined location
# coordinates for berkeley, california

lat = 37.87
lon = 122.27
ds_berk = ds.sel(lon=lon, lat=lat, method='nearest')

In [5]:
# converting to timeseries dataframe

sr = ds_berk['pr'].to_pandas()
sr.index = sr.index.to_datetimeindex()
df = pd.DataFrame({'time':sr.index, 'pr':sr.values})

/var/folders/bz/l7frggbx71n9k19wxh7hvwsm0000gn/T/ipykernel_47104/1416090827.py:4: RuntimeWarning: Converting a CFTimeIndex with dates from a non-standard calendar, 'noleap', to a pandas.DatetimeIndex, which uses dates from the standard calendar.  This may lead to subtle errors in operations that depend on the length of time between dates.
  sr.index = sr.index.to_datetimeindex()


## using climextremes to calculate extreme value

In [7]:
# get annual max series (ams)

ams = df.groupby([df.time.dt.year])['pr'].max()
ams = ams.reset_index()
ams

time         pr
0    1850   6.327219
1    1851   5.335728
2    1852   5.972910
3    1853  11.385193
4    1854   6.395780
..    ...        ...
151  2001   6.569665
152  2002   7.322962
153  2003   5.162756
154  2004   5.695780
155  2005   7.891376

[156 rows x 2 columns]

In [16]:
result = climext.fit_gev(np.array(ams.pr), returnPeriod = 10, returnValue = 8, 
                         getFit = True, getParams = True, bootSE = True)

In [17]:
#get return value from return period

result['returnValue']

array([8.25341018])

In [18]:
#get return value standard error

result['se_returnValue']

array([0.22249658])

In [19]:
#log of probability of exceeding 'returnValue'

result['logReturnProb']

array([-2.0959795])